# Generated by Django 3.2.6 on 2021-08-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('pubdate', models.CharField(max_length=8)),
                ('publisher', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
