# Generated by Django 3.2.5 on 2021-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
                'db_table': 'community_communities',
                'ordering': ('-date',),
            },
        ),
    ]
