# Generated by Django 3.2.6 on 2021-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='videolink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
