# Generated by Django 3.2.6 on 2021-09-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_videolink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='videolink',
            new_name='youtube_link',
        ),
    ]
